##Numpy: Numurical python 
numpy provides many mathematical operation function
faster as compared to other data structure 

In [2]:
import numpy as np
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [17]:
list1  = [[1,2,3,4],[5,6,7,8]] # list store hetrogenous data
arr = np.array(list1) # arrray is way to stror the homogenous type of data
print(arr)
print(type(arr),type(list1))
print(np.ndim(arr))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'> <class 'list'>
2


In [22]:
list2= [1,2,3,4,5,'NIQ']
arr2= np.array(list2)
arr2 # here type of integer change into string beacuse of numpy property

array(['1', '2', '3', '4', '5', 'NIQ'], dtype='<U11')

In [26]:
# 2 dimension array is way to store the data in the form of matrix 
arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9],[81,82,84,85,86]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [81, 82, 84, 85, 86]])

In [30]:
arr2[1,1] # indiex number starts from 0 

6

In [41]:
arr3 = np.array([1])
arr3

array([1])

In [42]:
np.ndim(arr3)

1

In [43]:
np.shape(arr2)
np.shape(arr3)

(1,)

In [51]:
m1 =np.matrix([1,2,3,4,5]) # matrix by defaulut 2-dimesnion array 

matrix([[1, 2, 3, 4, 5]])

In [53]:
arr4 = np.array(m1)
arr4

array([[1, 2, 3, 4, 5]])

In [54]:
arr5 = np.asanyarray(m1)
arr5

matrix([[1, 2, 3, 4, 5]])

In [57]:
arr6 = np.asarray(m1)
arr6

array([[1, 2, 3, 4, 5]])

In [61]:
t1 = ("hi")
print(type(t1))

<class 'str'>


In [66]:
thisset = {"apple", "banana", "cherry",1,23}

print(thisset)

{1, 'banana', 23, 'cherry', 'apple'}


In [3]:
arr4 = np.empty((3,4))

In [4]:
arr4

array([[1.02259663e-311, 2.76676762e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.16095484e-028, 2.87856340e-014,
        7.52736939e+252],
       [2.09603058e-110, 6.48224637e+170, 3.67145870e+228,
        1.22151092e+295]])

In [7]:
arr8 = np.zeros((3,4),dtype=int)

In [8]:
arr8

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
arr8.flatten()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
list1 = [[[1,2,3],[4,5,7],[8,9,7]]]

In [24]:
arr3 = np.array(list1)

In [25]:
np.ndim(arr3)

3

In [26]:
arr3

array([[[1, 2, 3],
        [4, 5, 7],
        [8, 9, 7]]])

In [27]:
np.shape(arr3)

(1, 3, 3)

In [28]:
arr5 = np.zeros((2,3,4))
arr5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
np.ndim(arr5)

3

In [32]:
np.shape(arr5)

(2, 3, 4)

In [42]:
arr6 = np.random.randint(1,10,(5,6))

In [43]:
arr6

array([[6, 4, 7, 3, 8, 3],
       [5, 4, 1, 5, 6, 5],
       [6, 4, 7, 5, 1, 3],
       [6, 1, 9, 8, 1, 9],
       [5, 9, 7, 1, 4, 1]])

In [44]:
# i want to find wether the number are greter than 5
arr6>5

array([[ True, False,  True, False,  True, False],
       [False, False, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [ True, False,  True,  True, False,  True],
       [False,  True,  True, False, False, False]])

In [48]:
arr6

array([[6, 4, 7, 3, 8, 3],
       [5, 4, 1, 5, 6, 5],
       [6, 4, 7, 5, 1, 3],
       [6, 1, 9, 8, 1, 9],
       [5, 9, 7, 1, 4, 1]])

In [49]:
arr6[arr6>5] # give me all the values in the array where condiation is true

array([6, 7, 8, 6, 6, 7, 6, 9, 8, 9, 9, 7])

In [50]:
arr7 = np.random.randint(1,25,(5,10))
arr7

array([[13, 18, 15, 10, 21,  7,  7,  3, 14, 18],
       [ 9, 21, 16, 10, 14, 18, 21,  6, 19, 20],
       [12,  2,  2, 13, 11,  1,  1, 14,  3, 18],
       [ 3, 13,  1,  8,  8,  8, 24, 23, 13, 22],
       [21, 15,  2,  3, 18, 15, 13, 10, 24, 22]])

In [76]:
arr7

array([[13, 18, 15, 10, 21,  7,  7,  3, 14, 18],
       [ 9, 21, 16, 10, 14, 18, 21,  6, 19, 20],
       [12,  2,  2, 13, 11,  1,  1, 14,  3, 18],
       [ 3, 13,  1,  8,  8,  8, 24, 23, 13, 22],
       [21, 15,  2,  3, 18, 15, 13, 10, 24, 22]])

In [56]:
arr7[(0,1)]

18

# to extract rows and columns from numpy array use following syntax
arr[row_start:row_end, col_start:col_end]


In [86]:
arr7[0:3,0:3]

array([[13, 18, 15],
       [ 9, 21, 16],
       [12,  2,  2]])

In [80]:
arr7[0:4] # here we are going to extract first 4 rows and all columns

array([[13, 18, 15, 10, 21,  7,  7,  3, 14, 18],
       [ 9, 21, 16, 10, 14, 18, 21,  6, 19, 20],
       [12,  2,  2, 13, 11,  1,  1, 14,  3, 18],
       [ 3, 13,  1,  8,  8,  8, 24, 23, 13, 22]])

In [82]:
arr7[0:4,[0,3]]  # here we are going to extract 0,3 index number from first row 

array([[13, 10],
       [ 9, 10],
       [12, 13],
       [ 3,  8]])

In [71]:
arr7[0,[1,3]]

array([18, 10])

In [72]:
arr7[0][1:3]

array([18, 15])

In [64]:
list2 = np.zeros((3,3))

In [87]:
arr7

array([[13, 18, 15, 10, 21,  7,  7,  3, 14, 18],
       [ 9, 21, 16, 10, 14, 18, 21,  6, 19, 20],
       [12,  2,  2, 13, 11,  1,  1, 14,  3, 18],
       [ 3, 13,  1,  8,  8,  8, 24, 23, 13, 22],
       [21, 15,  2,  3, 18, 15, 13, 10, 24, 22]])

array([[13, 18, 15, 10, 21,  7,  7,  3, 14, 18]])

In [94]:
mat1 = np.matrix(list2,dtype=int)
mat1

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

if we have two matrix (2d numpy array) first matrix with m*n  and p*q
m is number of rows of first matrix
n is number of columns of first matrix
p is number of rows of second matrix
q is number of columns of second matrix

so matrix multiplication takes only when  number of columns of first matrix is equal to number of rows of second matrix 
means n=q and their dimension are 

In [95]:
a = np.random.randint(1,5,(3,4))
a

array([[1, 3, 2, 2],
       [4, 2, 2, 1],
       [1, 2, 3, 3]])

In [107]:
b = np.random.randint(1,9,(3,2))
b

array([[5, 1],
       [8, 2],
       [4, 5]])

In [99]:
a @ b

array([[43, 48],
       [50, 63],
       [44, 48]])

In [100]:
a/0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5848\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [105]:
arr9 = np.zeros((3,3),dtype=int)
arr9

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [110]:
v = np.array([1,2,3])

In [111]:
arr9 +v

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [112]:
a

array([[1, 3, 2, 2],
       [4, 2, 2, 1],
       [1, 2, 3, 3]])

In [113]:
np.sum(a)

26

In [114]:
np.sum(a,axis=1)

array([8, 9, 9])

In [115]:
np.sum(a,axis=0)

array([6, 7, 7, 6])