<img src="skills_logo-removebg-preview.png" height="70">

### 1. What is a Python library? Why do we use Python libraries?

ANS : A Python library is a collection of modules, which can include functions, classes, and variables that you can use to simplify coding tasks. Libraries are often optimized for specific purposes, like mathematical computations, data analysis, or web development. You can use the functions and classes in these libraries without writing them from scratch, making your code more efficient and easier to maintain.

For example, with a library like NumPy, you can perform complex numerical calculations using pre-optimized functions and classes designed for performance. Libraries allow for code reuse and help reduce development time.

### 2. What is the difference between Numpy array and List?

List:

Definition: A list is a built-in Python data structure that can hold heterogeneous data (i.e., elements of different data types like integers, strings, floats, etc.).

Flexibility: It can grow or shrink dynamically and store multiple types of data.

Speed: Lists are flexible but can be slower compared to NumPy arrays when performing mathematical operations because they are not optimized for such tasks.

NumPy Array:

Definition: A NumPy array is a special data structure provided by the NumPy library, specifically designed for numerical computation. It is a linear data structure that holds homogeneous data (all elements must be of the same type, usually numbers like integers or floats).

Efficiency: NumPy arrays are faster and more memory-efficient than lists, especially for mathematical and scientific operations. This is because NumPy arrays are implemented in C and use contiguous memory blocks, allowing efficient access and computation.

Operations: NumPy arrays support vectorized operations, meaning you can perform element-wise operations without needing to write loops, which is a key advantage for performance.

### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

ANS: 

In [6]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(f'shape of array is: {np.shape(arr)}') # it will return  number of rows and columns in the form of tuple 
print(f'dimension of array is : {np.ndim(arr)}') # it will number of dimensionn 
print(f'size of array is : {np.size(arr)}') # it will return number of element means rows*columns 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of array is: (3, 4)
dimension of array is : 2
size of array is : 12


### 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

ANS :

In [7]:
arr[0] # we acn access first row of arry by index number 0

array([1, 2, 3, 4])

### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

ANS :

In [8]:
arr[2,3]

12

### 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

ANS:

In [23]:
a = arr.flatten()
for i,j in enumerate(a):
    if i%2!=0:
        print(f'odd index number {i}')

odd index number 1
odd index number 3
odd index number 5
odd index number 7
odd index number 9
odd index number 11


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?


ANS : 

In [26]:
arr2 = np.random.sample((3,3))
m1 = np.matrix(arr2)
print(m1)
print(type(m1))

[[0.12727989 0.57506478 0.0849878 ]
 [0.29903385 0.25286499 0.19254136]
 [0.21375231 0.52271952 0.32045301]]
<class 'numpy.matrix'>


### 8. Describe the difference between np.random.rand and np.random.randn?

ANS:

np.random.rand(): This function generates an array of the given shape filled with random samples from a uniform distribution over the interval of 0,1

np.random.randn (): This function generates an array of the given shape filled with random samples from the standard normal distribution mean is 0 &standard deviation is 1


### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],


[9, 10, 11, 12]]

ANS:

In [53]:
print(np.ndim(arr)) 
print(arr)
# with the help of np.expand_dim () we can increase dimension with the adding axis=o wher we add new axis at row and axis=1 when we add  columns
arr3 = np.expand_dims(arr,axis=1)
print(arr3)
arr4 = arr3.reshape(1,1,3,4) # using reshape wher axis=0
print(arr4)
print(np.ndim(arr4))

2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]
4


### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

ANS

In [54]:
arr.T # using Transpose (T)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [58]:
np.swapaxes(arr,0,1) # using swapaxes

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

Index wise multiplication

Matrix multiplication

Add both the matrix

Subtract matrix B from 

divide Matrix B by A

ANS

In [66]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a*b # multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [74]:
# to perform matrix mltiplication m*n & p*q  where n=p so we will transponse b and then perform matrix multiplication
m = a@b.T
m

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [76]:
a+b # using + addition operator

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [77]:
np.add(a,b) # using add method

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [79]:
np.subtract(b,a) # using substract method

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
b-a # using operator 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [82]:
b/a # division 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 12. Which function in Numpy can be used to swap the byte order of an array?

ANS

The function used to swap the byte order of an array in NumPy is numpy.ndarray.byteswap(). This function is often used when working with data formats that have a different endianness.

In [85]:
arr
arr5 = arr.byteswap()
arr5

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

### 13. What is the significance of the np.linalg.inv function?

ANS

The np.linalg.inv() function is used to compute the inverse of a square matrix.The inverse of a matrix A is a matrix B such that when A is multiplied by B,the result is the identity matrix. This function is significant in linear algebra,particularly in solving systems of linear equations, where you can find solutions ,by multiplying the inverse of a matrix by a vector

### 15. What is broadcasting in NumPy?

ANS

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. When two arrays are operated on, NumPy compares their shapes and applies the following rules to make them compatible:

If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes are the same.
If the sizes of the two arrays in any dimension are different and one of the sizes is not 1, an error is raised.
If the size of one of the arrays is 1 in a particular dimension, NumPy treats that dimension as if it were the size of the other array.

In [86]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([10, 20, 30])  
a+b

array([[11, 22, 33],
       [14, 25, 36]])